version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: db123
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
    ports:
      - "5432:5432"
    volumes:
      - ./init-sandbox.sql:/docker-entrypoint-initdb.d/init-sandbox.sql
      - ./initusersql.sql:/docker-entrypoint-initdb.d/initusersql.sql

  api:
    image: selectstarserver:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=db123
      - ADMIN_USER=admin
      - ADMIN_PASS=admin_pass
      - STUDENT_USER=selectStar
      - STUDENT_PASS=pass1234